import { tv } from 'tailwind-variants';

export const fallbackVariants = tv({
  slots: {
    container: [
      'flex',
      'items-center',
      'justify-center',
      'min-h-screen',
      'bg-gradient-to-br',
      'from-gray-50',
      'to-gray-100',
      'px-6',
      'py-12',
    ],
    contentWrapper: ['text-center', 'max-w-2xl', 'mx-auto', 'space-y-6'],
    errorCode: [
      'text-9xl',
      'md:text-[12rem]',
      'font-black',
      'text-transparent',
      'bg-clip-text',
      'bg-gradient-to-r',
      'from-blue-600',
      'to-purple-600',
      'leading-none',
      'select-none',
    ],
    heading: ['text-4xl', 'md:text-5xl', 'font-bold', 'text-gray-900', 'tracking-tight'],
    description: ['text-lg', 'md:text-xl', 'text-gray-600', 'max-w-lg', 'mx-auto', 'leading-relaxed'],
    ctaWrapper: ['flex', 'flex-col', 'sm:flex-row', 'gap-4', 'justify-center', 'items-center', 'mt-8'],
    primaryButton: [
      'inline-flex',
      'items-center',
      'justify-center',
      'px-8',
      'py-3',
      'text-base',
      'font-medium',
      'text-white',
      'bg-blue-600',
      'border',
      'border-transparent',
      'rounded-lg',
      'hover:bg-blue-700',
      'focus:outline-none',
      'focus:ring-2',
      'focus:ring-offset-2',
      'focus:ring-blue-500',
      'transition-colors',
      'duration-200',
      'min-w-[180px]',
    ],
    secondaryButton: [
      'inline-flex',
      'items-center',
      'justify-center',
      'px-8',
      'py-3',
      'text-base',
      'font-medium',
      'text-gray-700',
      'bg-white',
      'border',
      'border-gray-300',
      'rounded-lg',
      'hover:bg-gray-50',
      'focus:outline-none',
      'focus:ring-2',
      'focus:ring-offset-2',
      'focus:ring-blue-500',
      'transition-colors',
      'duration-200',
      'min-w-[180px]',
    ],
  },
});
