import { tv } from 'tailwind-variants';

export const languageSelectorVariants = tv({
  slots: {
    base: ['relative'],
    buttonClasses: [
      'flex',
      'items-center',
      'gap-3',
      'px-4',
      'py-2.5',
      'rounded-lg',
      'transition-all',
      'duration-200',
      'hover:bg-gray-50',
      'focus:outline-none',
      'focus:ring-2',
      'focus:ring-blue-500',
      'focus:ring-offset-1',
      'border',
      'border-gray-200',
      'bg-white',
      'shadow-sm',
      'hover:shadow-md',
      'hover:border-gray-300',
    ],
    buttonContainer: ['flex', 'items-center', 'gap-3', 'min-w-0'],
    countryNameWrapper: ['flex', 'flex-col', 'min-w-0', 'flex-1'],
    countryText: ['text-sm', 'font-semibold', 'text-gray-900', 'leading-tight', 'truncate'],
    languageText: ['text-xs', 'font-normal', 'text-gray-600', 'leading-tight', 'truncate'],
    dropDownMenuWrapper: [
      'absolute',
      'top-full',
      'right-0',
      'md:min-w-[200px]',
      'mt-2',
      'bg-white',
      'rounded-lg',
      'shadow-lg',
      'border',
      'border-gray-200',
      'overflow-hidden',
      'transition-all',
      'duration-200',
      'origin-top',
      'z-30',
    ],
    dropDownMenuList: ['py-1', 'max-h-[300px]', 'overflow-y-auto'],
    dropDownMenuItem: [
      'flex',
      'items-center',
      'justify-between',
      'gap-3',
      'px-4',
      'py-2.5',
      'text-sm',
      'text-gray-700',
      'transition-colors',
      'duration-150',
      'cursor-pointer',
      'hover:bg-gray-50',
      'focus:bg-gray-50',
      'focus:outline-none',
      'border-l-2',
      'border-transparent',
      'hover:border-blue-500',
      'hover:text-gray-900',
      'w-full',
      'text-left',
    ],
    dropDownItemName: ['flex', 'flex-col', 'min-w-0', 'flex-1'],
    chevronContainer: ['flex', 'items-center', 'justify-center', 'ml-auto'],
    buttonIcon: ['h-4', 'w-4', 'text-gray-500', 'transition-transform', 'duration-200'],
  },
  variants: {
    isOverlayVisible: {
      true: {
        dropDownMenuWrapper: ['scale-100', 'opacity-100', 'visible', 'pointer-events-auto'],
        buttonIcon: ['rotate-180', 'text-blue-600'],
        buttonClasses: ['ring-2', 'ring-blue-500', 'ring-offset-1', 'border-blue-500'],
      },
      false: {
        dropDownMenuWrapper: ['scale-95', 'opacity-0', 'invisible', 'pointer-events-none'],
        buttonIcon: ['rotate-0'],
      },
    },
  },
});
