/**
 * @file fetch-language.ts
 * @description CLI script to fetch available languages/locales from Contentstack and generate TypeScript constants.
 * Queries the Contentstack Management API to retrieve all configured locales and creates a type-safe
 * constants file for locale configuration throughout the application.
 *
 * This script should be run during the build process or when locale configuration changes in Contentstack.
 *
 * Usage:
 * npm run fetch-language
 * or
 * tsx scripts/fetch-language.ts
 *
 * Requirements:
 * - CONTENTSTACK_MANAGEMENT_TOKEN must be set in .env file
 * - CONTENTSTACK_API_KEY must be set in .env file
 *
 * Output:
 * - Generates constants/locales.ts with:
 *   - SUPPORTED_LOCALES array
 *   - DEFAULT_LOCALE constant
 *   - LANGUAGE_DETAILS with native names and ISO codes
 *   - TypeScript types for type-safe locale handling
 *
 * @see {@link https://www.contentstack.com/docs/developers/apis/content-management-api/}
 */

import * as fs from 'fs';
import * as path from 'path';

import { fetchLocales, testConnection } from '../lib/contentstack/management-stack';
import { Locale } from '@contentstack/management/types/stack/locale';

/**
 * Script configuration settings.
 */
const CONFIG = {
    /** Output file path for generated TypeScript constants */
    outputFile: path.join(process.cwd(), 'constants', 'locales.ts'),
} as const;

/**
 * Logger utility for consistent console output formatting.
 * Provides semantic logging methods with emoji prefixes.
 */
const logger = {
    info: (message: string) => console.log(`ℹ️  ${message}`),
    success: (message: string) => console.log(`✅ ${message}`),
    warn: (message: string) => console.warn(`⚠️  ${message}`),
    error: (message: string) => console.error(`❌ ${message}`),
    debug: (message: string) => console.log(`🔍 ${message}`),
};

/**
 * Processes raw locale data from Contentstack into structured format.
 * Extracts locale codes, determines the default locale, and creates detailed language information.
 *
 * @param {Locale[]} languages - Array of locale objects from Contentstack Management API
 * @returns {Object} Processed locale configuration with locales, default, and details
 */
function processLocales(languages: Locale[]) {
    logger.debug(`Processing ${languages.length} locales`);

    // Extract all locale codes
    const locales = languages.map((lang) => lang.code);

    // Determine default locale (locale without fallback or first in list)
    const defaultLocale =
        languages.find((lang) => !lang.fallback_locale || lang.fallback_locale === lang.code)?.code ||
        locales[0];

    if (!defaultLocale) {
        throw new Error('Could not determine default locale from stack');
    }

    // Create detailed language information with native names and ISO codes
    const languageDetails = languages
        .map((lang) => {
            const isoCode = lang.code.split('-')[0]; // e.g., "en" from "en-us"
            const langCode = lang.code;

            // Extract native name from the name field (part before " - ")
            const nativeName = lang.name.split(' - ')[0].trim();
            const countryName = lang.name.includes(' - ') ? lang.name.split(' - ')[1].trim() : null;

            return {
                countryName,
                nativeName,
                isoCode,
                langCode,
            };
        })
        .sort((a, b) => a.nativeName.localeCompare(b.nativeName)); // Sort alphabetically by native name

    logger.debug(`Default locale: ${defaultLocale}`);

    return {
        locales,
        defaultLocale,
        languageDetails,
    };
}

/**
 * Generates TypeScript file content with locale constants and types.
 * Creates a fully-typed constants file with JSDoc documentation.
 *
 * @param {ReturnType<typeof processLocales>} data - Processed locale configuration
 * @returns {string} Complete TypeScript file content
 */
function generateTypeScriptContent(data: ReturnType<typeof processLocales>): string {
    return `/**
 * Locale Constants
 * 
 * This file is auto-generated by scripts/fetch-language.ts
 * 
 * @see scripts/fetch-language.ts
 * 
 * DO NOT EDIT MANUALLY - Changes will be overwritten on next build
 */

export interface LanguageDetail {
  countryName: string | null; // Country name (extracted from Contentstack)
  nativeName: string; // Language name in its native script (extracted from Contentstack)
  isoCode: string; // ISO 639-1 language code (e.g., "en", "fr")
  langCode: string; // Language code (e.g., "en", "fr", "en-us", "tr-tr")
}

// Available locales in the Contentstack stack
export const SUPPORTED_LOCALES = ${JSON.stringify(data.locales, null, 2)} as const;

// Default locale for the application
export const DEFAULT_LOCALE = '${data.defaultLocale}' as const;

// TypeScript type for supported locales
export type SupportedLocale = (typeof SUPPORTED_LOCALES)[number];

/**
 * Detailed language information
 * Includes country code, native name, and ISO language code
 */

export const LANGUAGE_DETAILS: LanguageDetail[] = ${JSON.stringify(data.languageDetails, null, 2)};

/**
 * Languages that should not appear in URL paths
 * Typically includes the default language to keep URLs clean
 */
export const LANGUAGES_WITHOUT_URL_PREFIX = [DEFAULT_LOCALE as string];
`;
}

/**
 * Writes the generated TypeScript content to the output file.
 * Creates the output directory if it doesn't exist.
 *
 * @param {string} content - TypeScript file content to write
 */
function writeOutputFile(content: string): void {
    const outputDir = path.dirname(CONFIG.outputFile);

    // Ensure output directory exists
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
        logger.info(`Created directory: ${outputDir}`);
    }

    // Write the generated TypeScript file
    fs.writeFileSync(CONFIG.outputFile, content, 'utf-8');

    logger.success(`Generated: ${CONFIG.outputFile}`);
}

/**
 * Main execution function.
 * Orchestrates the entire language fetching and generation process:
 * 1. Tests Contentstack API connection
 * 2. Fetches locales from stack
 * 3. Processes locale data
 * 4. Generates TypeScript file
 * 5. Writes output file
 *
 * @returns {Promise<void>}
 */
async function main(): Promise<void> {
    logger.info('Starting language fetch from Contentstack...');

    try {
        // Step 1: Test Contentstack Management API connection
        logger.info('Testing Contentstack Management API connection...');
        await testConnection();
        logger.success('Connection successful');

        // Step 2: Fetch locales from Contentstack stack
        logger.info('Fetching locales from stack...');
        const languages = await fetchLocales();

        if (languages.length === 0) {
            throw new Error('No locales found in Contentstack stack');
        }

        logger.success(`Found ${languages.length} locale${languages.length > 1 ? 's' : ''}`);
        languages.forEach((lang) => {
            logger.info(`  - ${lang.code} (${lang.name})`);
        });

        // Step 3: Process locale data into structured format
        logger.info('Processing locale data...');
        const processedData = processLocales(languages);

        // Step 4: Generate TypeScript file content
        logger.info('Generating TypeScript file...');
        const fileContent = generateTypeScriptContent(processedData);

        // Step 5: Write output file
        writeOutputFile(fileContent);

        // Display success summary
        logger.success('Language fetch complete!');
        logger.info(`  Locales: ${processedData.locales.join(', ')}`);
        logger.info(`  Default: ${processedData.defaultLocale}`);
        logger.info(`  Output: ${CONFIG.outputFile}`);
    } catch (error) {
        logger.error('Language fetch failed');

        if (error instanceof Error) {
            logger.error(error.message);

            // Provide helpful error messages based on error type
            if (error.message.includes('CONTENTSTACK_MANAGEMENT_TOKEN')) {
                logger.info('Hint: Make sure your .env file contains CONTENTSTACK_MANAGEMENT_TOKEN');
                logger.info('      You can generate one at: Settings → Tokens → Management Tokens');
            } else if (error.message.includes('CONTENTSTACK_API_KEY')) {
                logger.info('Hint: Make sure your .env file contains CONTENTSTACK_API_KEY');
            } else if (error.message.includes('authentication')) {
                logger.info(
                    'Hint: Check that your CONTENTSTACK_MANAGEMENT_TOKEN is valid and has appropriate permissions'
                );
            }
        }

        // Exit with error code
        process.exit(1);
    }
}

// Execute the main function and handle promise resolution
main()
    .then(() => {
        process.exit(0); // Exit successfully
    })
    .catch((error) => {
        logger.error(`Unexpected error: ${error instanceof Error ? error.message : 'Unknown error'}`);
        process.exit(1); // Exit with error code
    });
